-- MySQL Script generated by MySQL Workbench

-- Thu Jun 15 10:14:09 2023

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;

-- -----------------------------------------------------

-- Schema inovin

-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `inovin` DEFAULT CHARACTER SET utf8 ;

USE `inovin` ;

-- -----------------------------------------------------

-- Table `inovin`.`winery`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`winery` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `name` VARCHAR(45) NOT NULL,
        `productor_name` VARCHAR(45) NULL,
        `address` VARCHAR(100) NULL,
        `zip_code` VARCHAR(45) NULL,
        `city` VARCHAR(45) NULL,
        `website` LONGTEXT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`winery` (
        name,
        productor_name,
        address,
        zip_code,
        city,
        website
    )
VALUES (
        'Château de Chambert',
        NULL,
        NULL,
        NULL,
        NULL,
        'https://www.chateaudechambert.com'
    ), (
        'Château Latour',
        NULL,
        NULL,
        NULL,
        'Pauillac',
        'https://www.chateau-latour.com'
    ), (
        'Domaine Jean-Louis Chave',
        NULL,
        NULL,
        NULL,
        'Hermitage',
        NULL
    ), (
        'Domaine Leflaive',
        NULL,
        NULL,
        NULL,
        'Puligny-Montrachet',
        NULL
    ), (
        'Château Pétrus',
        NULL,
        NULL,
        NULL,
        'Pomerol',
        NULL
    ), (
        'Domaine de la Romanée-Conti',
        NULL,
        NULL,
        NULL,
        'Vosne-Romanée',
        NULL
    ), (
        'Domaine Pascal Jolivet',
        NULL,
        NULL,
        NULL,
        'Sancerre',
        'http://www.pascaljolivet.com'
    ), (
        'Domaine Zind-Humbrecht',
        NULL,
        NULL,
        NULL,
        'Alsace',
        'https://www.zindhumbrecht.fr'
    ), (
        'Château Soucherie',
        NULL,
        NULL,
        NULL,
        'Anjou,Loire',
        'https://www.soucherie.fr/'
    );

-- -----------------------------------------------------

-- Table `inovin`.`wine_region`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`wine_region` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `name` VARCHAR(55) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`wine_region` (`name`)
VALUES ('Alsace'), ('Lorraine'), ('Bordeaux'), ('Beaujolais'), ('Lyonnais'), ('Bourgogne'), ('Champagne'), ('Corse'), ('Provence'), ('Jura'), ('Savoie'), ('Bugey'), ('Languedoc-Roussillon'), ('Sud-Ouest'), ('Vallée de la Loire'), ('Vallée du Rhône');

-- -----------------------------------------------------

-- Table `inovin`.`grape_variety`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`grape_variety` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `name` VARCHAR(45) NOT NULL,
        `description` LONGTEXT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`grape_variety` (name, description)
VALUES (
        'Abouriou',
        'Cépage rouge originaire du Sud-Ouest de la France, produit des vins corsés et fruités'
    ), (
        'Aligoté',
        'Cépage blanc de Bourgogne, donne des vins frais et vifs, souvent utilisé pour produire le célèbre Kir'
    ), (
        'Alicante Bouschet',
        'Cépage rouge à pulpe rouge foncé, apporte de la couleur et de la structure aux assemblages'
    ), (
        'Aramon',
        'Ancien cépage rouge du Languedoc, produit des vins légers et fruités, principalement utilisé pour la production de vin de table'
    ), (
        'Arbois',
        'Cépage blanc du Jura, donne des vins aromatiques avec une acidité rafraîchissante'
    ), (
        'Auxerrois',
        "Cépage blanc de la région d'Alsace, souvent utilisé pour produire des vins d'assemblage avec le Pinot Blanc"
    ), (
        'Baco Blanc',
        'Cépage blanc utilisé principalement pour produire le célèbre Armagnac'
    ), (
        'Baco Noir',
        "Cépage rouge hybride, utilisé notamment dans la production d'Armagnac et de vins de table"
    ), (
        'Barbera',
        'Cépage rouge italien largement cultivé en Piémont, produit des vins fruités et acides'
    ), (
        'Biancone',
        'Cépage blanc de Corse, utilisé pour produire des vins corsés et aromatiques'
    ), (
        'Blanquette',
        'Cépage blanc principalement utilisé dans la production de vins effervescents de Limoux, notamment la Blanquette de Limoux'
    ), (
        'Bobal',
        'Cépage rouge espagnol cultivé dans la région de Valence, donne des vins riches en couleur et en tanins'
    ), (
        'Bonarda',
        "Cépage rouge d'origine italienne, également cultivé en Argentine, produit des vins fruités et juteux"
    ), (
        'Braquet',
        'Cépage rouge du Sud de la France, utilisé pour produire des vins rosés aromatiques et fruités'
    ), (
        'Cabernet Franc',
        'Cépage rouge répandu en France, apporte des arômes de fruits rouges et des tanins souples'
    ), (
        'Cabernet Sauvignon',
        'Cépage rouge emblématique, cultivé dans le monde entier, donne des vins puissants et structurés, avec des arômes de cassis et de cèdre'
    ), (
        'Caladoc',
        'Cépage rouge hybride, résultat du croisement entre le Grenache et le Malbec, utilisé notamment dans la région du Languedoc'
    ), (
        'Calitor',
        'Cépage rouge hybride, croisement entre le Grenache et le Carignan, utilisé principalement dans le Sud-Ouest de la France'
    ), (
        'Camarese',
        'Cépage rouge ancien du Sud de la France, utilisé pour produire des vins rustiques et tanniques'
    ), (
        'Camaraou Noir',
        'Cépage rouge de la région du Béarn, produit des vins charnus et épicés'
    ), (
        'Carignan',
        'Cépage rouge méditerranéen, donne des vins riches en couleur, tanniques et souvent utilisés en assemblage'
    ), (
        'Carménère',
        'Cépage rouge originaire de Bordeaux, désormais principalement cultivé au Chili, produit des vins complexes avec des arômes de poivron et de fruits noirs'
    ), (
        'Chardonnay',
        'Cépage blanc originaire du vignoble de Bourgogne utilisé pour de nombreux types de vin blanc, des grands crus de Bourgogne aux vins effervescents de champagne. '
    ), (
        'Cinsault',
        'Cépage rouge de la région du Languedoc, souvent utilisé pour produire des vins rosés légers et fruités'
    ), (
        'Clairette',
        'Cépage blanc utilisé principalement dans la production de vins blancs secs et effervescents'
    ), (
        'Colombard',
        'Cépage blanc principalement utilisé pour produire des vins blancs secs et des vins effervescents'
    ), (
        'Côt',
        'Autre nom du cépage Malbec, utilisé notamment dans la région de Cahors en France'
    ), (
        'Counoise',
        'Cépage rouge de la Vallée du Rhône, souvent utilisé en assemblage pour ajouter de la couleur et de la fraîcheur'
    ), (
        'Courbu',
        'Cépage blanc de la région du Jurançon, utilisé pour produire des vins doux et moelleux'
    ), (
        'Durif',
        'Cépage rouge également connu sous le nom de Petite Sirah, originaire de France mais largement cultivé en Californie, donne des vins riches en couleur et en tanins'
    ), (
        'Fer Servadou',
        'Cépage rouge du Sud-Ouest de la France, utilisé pour produire des vins rouges corsés et épicés'
    ), (
        'Folle Blanche',
        "Cépage blanc principalement utilisé dans la production d'Armagnac et de Cognac"
    ), (
        'Gamay',
        'Cépage rouge emblématique du Beaujolais, produit des vins fruités et légers'
    ), (
        'Gewurztraminer',
        "Cépage blanc aromatique originaire d\'Alsace, donne des vins riches en arômes de litchi, de rose et d'épices"
    ), (
        'Grenache',
        'Cépage rouge méditerranéen, utilisé dans de nombreuses régions viticoles pour produire des vins puissants et fruités'
    ), (
        'Grenache Blanc',
        'Cépage blanc méditerranéen, utilisé notamment dans la production de vins blancs de la région du Rhône'
    ), (
        'Gros Manseng',
        'Cépage blanc du Sud-Ouest de la France, donne des vins aromatiques avec une acidité rafraîchissante'
    ), (
        'Jacquère',
        'Cépage blanc de Savoie, utilisé pour produire des vins frais et légers'
    ), (
        "Len de l'El",
        'Cépage blanc du Sud-Ouest de la France, utilisé pour produire des vins blancs secs et doux'
    ), (
        'Malbec',
        'Cépage rouge originaire de France, utilisé notamment dans la région de Cahors et en Argentine, produit des vins riches et structurés'
    ), (
        'Marsanne',
        'Cépage blanc de la Vallée du Rhône, utilisé pour produire des vins blancs riches et gras'
    ), (
        'Mauzac',
        'Cépage blanc principalement utilisé dans la production de vins effervescents, notamment la Blanquette de Limoux'
    ), (
        'Melon de Bourgogne',
        'Cépage blanc utilisé dans la production du Muscadet, donne des vins secs et minéraux'
    ), (
        'Merlot',
        'Cépage rouge largement cultivé dans le monde entier, donne des vins souples et fruités, souvent utilisés en assemblage'
    ), (
        'Molette',
        'Cépage blanc originaire de Savoie, utilisé pour produire des vins frais et légers'
    ), (
        'Mollard',
        'Cépage rouge du Sud de la France, utilisé pour produire des vins souples et fruités'
    ), (
        'Mondeuse',
        'Cépage rouge de Savoie, produit des vins rouges corsés et épicés'
    ), (
        'Mourvèdre',
        'Cépage rouge méditerranéen, apporte de la structure et des arômes épicés aux assemblages'
    ), (
        'Muscadelle',
        'Cépage blanc principalement utilisé dans la production de vins liquoreux, notamment dans la région de Sauternes'
    ), (
        'Muscardin',
        'Cépage rouge de la Vallée du Rhône, souvent utilisé en assemblage pour ajouter de la couleur et de la complexité'
    ), (
        'Muscat Blanc à Petits Grains',
        'Cépage blanc aromatique, utilisé pour produire des vins doux, moelleux et des vins effervescents'
    ), (
        "Muscat d'Alexandrie",
        'Cépage blanc utilisé pour produire des vins doux et moelleux, notamment dans le sud de la France et en Espagne'
    ), (
        'Nebbiolo',
        'Cépage rouge emblématique du Piémont en Italie, utilisé pour produire des vins tanniques et élégants, notamment le Barolo et le Barbaresco'
    ), (
        'Négrette',
        'Cépage rouge du Sud-Ouest de la France, utilisé pour produire des vins fruités et épicés'
    ), (
        'Nielluccio',
        'Cépage rouge de Corse, utilisé pour produire des vins corsés et tanniques'
    ), (
        'Petit Courbu',
        'Cépage blanc du Sud-Ouest de la France, utilisé pour produire des vins blancs secs et doux'
    ), (
        'Petit Manseng',
        'Cépage blanc du Sud-Ouest de la France, utilisé pour produire des vins doux et moelleux'
    ), (
        'Petit Verdot',
        'Cépage rouge utilisé principalement dans les assemblages bordelais, donne des vins riches en couleur et en tanins'
    ), (
        "Pineau d'Aunis",
        'Cépage rouge de la Vallée de la Loire, produit des vins légers et épicés'
    ), (
        'Pinot Blanc',
        'Cépage blanc de la famille des Pinots, utilisé pour produire des vins blancs frais et aromatiques'
    ), (
        'Pinot Gris',
        'Cépage blanc de la famille des Pinots, utilisé pour produire des vins blancs riches et aromatiques'
    ), (
        'Pinot Meunier',
        'Cépage noir de la famille des Pinots, utilisé principalement dans la production de Champagne'
    ), (
        'Pinot Noir',
        'Cépage noir de la famille des Pinots, utilisé dans de nombreuses régions viticoles pour produire des vins rouges fins et des vins effervescents'
    ), (
        'Poulsard',
        'Cépage rouge du Jura, produit des vins légers et fruités, souvent utilisés pour produire le Vin Jaune'
    ), (
        'Rolle',
        'Cépage blanc méditerranéen, également connu sous le nom de Vermentino, utilisé pour produire des vins blancs frais et aromatiques'
    ), (
        'Romorantin',
        'Cépage blanc ancien de la Loire, utilisé pour produire des vins blancs secs et aromatiques'
    ), (
        'Roussanne',
        'Cépage blanc de la Vallée du Rhône, utilisé pour produire des vins blancs riches et complexes'
    ), (
        'Sauvignon Blanc',
        'Cépage blanc aromatique, utilisé dans de nombreuses régions viticoles pour produire des vins frais et vifs, notamment le Sauvignon Blanc de la Loire et le Sauvignon Blanc de Marlborough'
    ), (
        'Sémillon',
        'Cépage blanc principalement utilisé dans la production de vins liquoreux, notamment dans la région de Sauternes'
    ), (
        'Syrah',
        'Cépage rouge emblématique du Rhône, utilisé dans de nombreuses régions viticoles pour produire des vins puissants et épicés'
    ), (
        'Tannat',
        'Cépage rouge originaire du Sud-Ouest de la France, produit des vins corsés et tanniques'
    ), (
        'Tempranillo',
        'Cépage rouge espagnol, utilisé notamment dans la production de vins de la Rioja et de la Ribera del Duero'
    ), (
        'Terret',
        'Cépage blanc du Languedoc, utilisé pour produire des vins frais et légers'
    ), (
        'Tibouren',
        'Cépage rouge de Provence, utilisé pour produire des vins rosés légers et aromatiques'
    ), (
        'Trousseau',
        'Cépage rouge du Jura, donne des vins rouges légers et aromatiques'
    ), (
        'Ugni Blanc',
        "Cépage blanc principalement utilisé pour produire des vins blancs secs et des eaux-de-vie, notamment le Cognac et l'Armagnac"
    ), (
        'Verdejo',
        'Cépage blanc espagnol, utilisé notamment dans la production de vins de la région de Rueda'
    ), (
        'Verdelho',
        'Cépage blanc principalement utilisé dans la production de vins de Madère'
    ), (
        'Vermentino',
        'Cépage blanc méditerranéen, également connu sous le nom de Rolle, utilisé pour produire des vins blancs frais et aromatiques'
    ), (
        'Viognier',
        'Cépage blanc aromatique de la Vallée du Rhône, utilisé pour produire des vins blancs riches et parfumés'
    );

-- -----------------------------------------------------

-- Table `inovin`.`existing_wine`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`existing_wine` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `vintage` VARCHAR(45) NOT NULL,
        `blend` VARCHAR(45) NULL,
        `color` VARCHAR(45) NOT NULL,
        `alcohol_percentage` INT NOT NULL,
        `picture` LONGTEXT NULL,
        `description` LONGTEXT NULL,
        `name` VARCHAR(45) NULL,
        `id_wine_region` INT NOT NULL,
        `id_grape_variety` INT NOT NULL,
        `id_winery` INT NOT NULL,
        PRIMARY KEY (`id`),
        CONSTRAINT `fk_existing_wine_wine_region1` FOREIGN KEY (`id_wine_region`) REFERENCES `inovin`.`wine_region` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_existing_wine_grape_variety1` FOREIGN KEY (`id_grape_variety`) REFERENCES `inovin`.`grape_variety` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_existing_wine_winery1` FOREIGN KEY (`id_winery`) REFERENCES `inovin`.`winery` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`existing_wine` (
        `vintage`,
        `blend`,
        `color`,
        `alcohol_percentage`,
        `picture`,
        `description`,
        `name`,
        `id_wine_region`,
        `id_grape_variety`,
        `id_winery`
    )
VALUES (
        'Malbec',
        '',
        'Rouge',
        13,
        '',
        '',
        '',
        14,
        40,
        1
    ), (
        'Cabernet Sauvignon',
        '',
        'Rouge',
        13,
        '',
        '',
        '',
        3,
        16,
        2
    ), (
        'Syrah',
        '',
        'Rouge',
        13,
        '',
        '',
        '',
        5,
        70,
        3
    ), (
        'Merlot',
        '',
        'Rouge',
        0,
        '',
        '',
        '',
        3,
        44,
        5
    ), (
        'Pinot Noir',
        '',
        'Rouge',
        12,
        '',
        '',
        '',
        6,
        63,
        6
    ), (
        'Sauvignon Blanc',
        '',
        'Blanc',
        13,
        '',
        '',
        '',
        15,
        68,
        7
    ), (
        'Gewurztraminer',
        '',
        'Blanc',
        12,
        '',
        '',
        '',
        1,
        34,
        8
    ), (
        'Chardonnay',
        '',
        'Blanc',
        12,
        '',
        '',
        '',
        6,
        23,
        6
    ), (
        'Pinot Gris',
        '',
        'Blanc',
        12,
        '',
        '',
        '',
        1,
        61,
        8
    ), (
        'Cabernet Franc',
        '',
        'Blanc',
        12,
        '',
        '',
        '',
        15,
        15,
        9
    );

-- -----------------------------------------------------

-- Table `inovin`.`appellation`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`appellation` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `name` VARCHAR(45) NULL,
        `label` VARCHAR(45) NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`appellation` (name)
VALUES ('Arbois'), ('Bandol'), ('Cahors'), ('Chablis'), ('Banyuls'), ('Beaujolais'), ('Bugey'), ('Cassis'), ('Clairette de Bellegarde'), ('Clairette de Die'), ('Clairette du Languedoc'), ('Condrieu'), ('Corbières'), ('Cornas'), ('Costières de Nîmes'), ('Côteaux d''Aix-en-Provence'), ('Côteaux d''Ancenis'), ('Côteaux du Giennois'), ('Côteaux du Languedoc'), ('Coteaux du Layon'), ('Côteaux du Loir'), ('Coteaux du Lyonnais'), ('Côteaux du Quercy'), ('Coteaux du Vendômois'), ('Côteaux du Verdon'), ('Coteaux Varois'), ('Coteaux-du-Layon'), ('Côtes de Beaune'), ('Côtes de Bergerac'), ('Côtes de Blaye'), ('Côtes de Bordeaux'), ('Côtes de Bourg'), ('Côtes de Castillon'), ('Côtes de Duras'), ('Côtes de Francs'), ('Côtes de Gascogne'), ('Côtes de Millau'), ('Côtes de Montravel'), ('Côtes de Nuits'), ('Côtes de Provence'), ('Côtes de Toul'), ('Côtes du Forez'), ('Côtes du Frontonnais'), ('Côtes du Jura'), ('Côtes du Marmandais'), ('Côtes du Rhône'), ('Côtes du Rhône-Villages'), ('Côtes du Roussillon'), (
        'Côtes du Roussillon-Villages'
    ), ('Côtes du Tarn'), ('Côtes du Ventoux'), ('Côtes du Vivarais'), ('Crémant d''Alsace'), ('Crémant de Bourgogne'), ('Crémant de Die'), ('Crémant de Limoux'), ('Crémant de Loire'), ('Crozes-Hermitage'), ('Entre-Deux-Mers'), ('Faugères'), ('Fitou'), ('Fleurie'), ('Floc de Gascogne'), ('Fronton'), ('Gaillac'), ('Haut-Médoc'), ('IGP Vin de Pays d''Oc'), (
        'IGP Vin de Pays de la Loire'
    ), (
        'IGP Vin de Pays des Côtes Catalanes'
    ), (
        'IGP Vin de Pays des Côtes de Gascogne'
    ), (
        'IGP Vin de Pays du Comté Tolosan'
    ), ('IGP Vin de Pays du Gard'), (
        'IGP Vin de Pays du Val de Loire'
    ), ('IGP Vin de Pays du Var'), (
        'IGP Vin de Pays du Vaucluse'
    ), ('Irouléguy'), ('Jurançon'), ('Lalande-de-Pomerol'), ('Lirac'), ('Madiran'), ('Malepère'), ('Marcillac'), ('Maury'), ('Menetou-Salon'), ('Mercurey'), ('Meursault'), ('Minervois'), ('Minervois-La Livinière'), ('Montagne-Saint-Émilion'), ('Montlouis-sur-Loire'), ('Morey-Saint-Denis'), ('Morgon'), ('Moulis-en-Médoc'), ('Muscadet'), (
        'Muscadet-Côtes de Grandlieu'
    ), (
        'Muscat de Beaumes-de-Venise'
    ), ('Muscat de Frontignan'), ('Muscat de Lunel'), ('Muscat de Mireval'), ('Muscat de Rivesaltes'), ('Pacherenc du Vic-Bilh'), ('Patrimonio'), ('Pauillac'), ('Pernand-Vergelesses'), ('Pessac-Léognan'), ('Pic Saint-Loup'), ('Picpoul de Pinet'), ('Pinot Noir d''Alsace'), ('Pomerol'), ('Pouilly-Vinzelles'), ('Quincy'), ('Rasteau'), ('Rivesaltes'), ('Roussette de Savoie'), ('Saint-Amour'), ('Saint-Chinian'), ('Saint-Émilion'), ('Saint-Estèphe'), ('Saint-Joseph'), ('Saint-Julien'), ('Saint-Julien'), ('Saint-Nicolas-de-Bourgueil'), ('Saint-Péray'), ('Saint-Pourçain'), ('Sancerre'), ('Saumur'), ('Saumur-Champigny'), ('Sauternes'), ('Savennières'), ('Tain-l''Hermitage'), ('Tavel'), ('Terrasses du Larzac'), ('Vacqueyras'), ('Ventoux'), ('Vin de Corse'), (
        'Vin de Pays de l''Atlantique'
    ), (
        'Vin de Pays de Méditerranée'
    ), ('Vin de Pays des Alpilles'), (
        'Vin de Pays des Coteaux de l''Ardèche'
    ), (
        'Vin de Pays des Côtes de Gascogne'
    ), (
        'Vin de Pays des Côtes de Thongue'
    ), ('Vin de Pays du Lot'), ('Vin de Pays du Tarn'), ('Vin de Pays du Vaucluse'), ('Vin de Savoie'), ('Vinsobres'), ('Vouvray');

-- -----------------------------------------------------

-- Table `inovin`.`user`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`user` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `firstname` VARCHAR(45) NOT NULL,
        `lastname` VARCHAR(45) NOT NULL,
        `birth_date` DATE NULL,
        `email` VARCHAR(45) NOT NULL,
        `hashed_password` VARCHAR(255) NOT NULL,
        `admin_credentials` TINYINT NOT NULL DEFAULT 0,
        `wine_color` VARCHAR(45) NULL,
        `preference_description` LONGTEXT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`user` (
        firstname,
        lastname,
        birth_date,
        email,
        hashed_password,
        admin_credentials,
        wine_color,
        preference_description
    )
VALUES (
        "Cyrille",
        "AQUILINA",
        "1990-07-20",
        "cyrille.aquilina@gmail.com",
        "$argon2id$v=19$m=65536,t=3,p=1$EED3J3qL48xtdO+6Onzl8w$v29dbf4",
        1,
        "Blanc",
        "Je les préfère bien sucrés!!!"
    ), (
        "Jérôme",
        "VILANOVA",
        "1983-05-11",
        "jerome.vilanova@gmail.com",
        "$argon2id$v=19$m=65536,t=3,p=1$2IzUb/JMAlnxRNSHg3g1NQ$zL5OI3I",
        1,
        "Rouge",
        "En toute modestie, je dirai que les vins de Gaillac sont les meilleurs du monde."
    ), (
        "Lambda",
        "User",
        "1990-09-20",
        "lambda.user@mail.com",
        "$argon2id$v=19$m=65536,t=3,p=1$xnCxPMemmygcPnMemighJQ$rPRYmKA",
        0,
        "Blanc",
        "tout!!!"
    );

-- -----------------------------------------------------

-- Table `inovin`.`competition_selection`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`competition_selection` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `competition_name` VARCHAR(100) NOT NULL,
        `commentary` LONGTEXT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`competition_selection` (competition_name, commentary)
VALUES ('Vinalies France', ''), (
        'Challenge international du vin',
        ''
    );

-- -----------------------------------------------------

-- Table `inovin`.`new_wine`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`new_wine` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `color` VARCHAR(45) NOT NULL,
        `selected_for_competition` TINYINT(0) DEFAULT 0 NULL,
        `commentary` LONGTEXT NULL,
        `id_competition_selection` INT NULL,
        PRIMARY KEY (`id`),
        CONSTRAINT `fk_new_wine_competition_selection1` FOREIGN KEY (`id_competition_selection`) REFERENCES `inovin`.`competition_selection` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`new_wine`(
        color,
        selected_for_competition,
        commentary,
        id_competition_selection
    )
VALUES (
        'Rouge',
        1,
        'Vin réalisé par Monsieur Vilanova - Qualité : Excellente',
        1
    ), (
        'Rouge',
        0,
        'Vin réalisé par Monsieur Cassagne - Qualité:  Sublime',
        2
    ), ('Rouge', 0, 'Médiocre', 1), (
        'Blanc',
        0,
        'Qualité moyenne',
        1
    ), (
        'Blanc',
        1,
        'Vin réalisé par Monsieur Aquilina Parfaitement équilibré',
        2
    );

-- -----------------------------------------------------

-- Table `inovin`.`workshop`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`workshop` (
        `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        `datetime` DATETIME NOT NULL,
        `place` VARCHAR(55) NOT NULL,
        `commentary` LONGTEXT NULL,
        `wine_type` VARCHAR(45) NULL
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`workshop` (
        datetime,
        place,
        commentary,
        wine_type
    )
VALUES (
        "2023/07/20 16:00:00",
        "Toulouse",
        "Ne manquez pas cet atelier d'inauguration du premier atelier de notre programme! Plongez dans l'univers envoûtant des vins rouges et laissez-vous séduire par une sélection exquise de cépages prestigieux. Nos sommeliers passionnés vous guideront à travers un voyage sensoriel, révélant les secrets de chaque vin. Préparez-vous à vivre une expérience inoubliable, où convivialité et découverte se mêlent harmonieusement.",
        "Rouge"
    ), (
        "2023/07/22 16:00:00",
        "Toulouse",
        "Nous vous invitons chaleureusement à l'inauguration du deuxième atelier de notre programme. Cette fois-ci, nous mettons à l'honneur les vins blancs, symboles de fraîcheur et d'élégance. Laissez-vous surprendre par notre sélection soigneusement choisie, mettant en lumière des appellations renommées et des cépages emblématiques. Nos experts vous dévoileront les secrets de ces nectars délicats, vous offrant ainsi une expérience gustative unique et enrichissante.",
        "Blanc"
    ), (
        "2023/07/22 19:00:00",
        "Toulouse",
        "Accordez vos sens lors de cet atelier exceptionnel dédié aux accords mets et vins. Plongez dans l'art subtil de marier harmonieusement les saveurs pour créer des expériences culinaires inoubliables. Nos chefs talentueux vous présenteront une sélection de mets savoureux, soigneusement associés à des vins d'exception. Vous découvrirez les subtilités des accords et apprendrez les principes fondamentaux pour créer vos propres harmonies gustatives. Préparez-vous à vivre une expérience gastronomique hors du commun, où l'équilibre des saveurs sera à l'honneur.",
        "Rouge"
    ), (
        "2023/07/24 14:00:00",
        "Bordeaux",
        "Plongez dans l'univers passionnant des vins rouges bio lors de cet atelier de dégustation unique. Explorez une sélection exclusive de crus biologiques, issus de terroirs d'exception. Vous découvrirez comment ces vins préservent l'expression authentique du fruit tout en respectant l'environnement.",
        "Rouge"
    ), (
        "2023/07/31 15:30:00",
        "Lyon",
        "Rejoignez-nous pour une expérience effervescente lors de cet atelier dédié aux vins pétillants du monde entier. Des champagnes aux proseccos en passant par les crémants, vous découvrirez la diversité des vins effervescents et leurs caractéristiques uniques. ",
        "Blanc"
    ), (
        "2023/07/31 18:00:00",
        "Lyon",
        "Laissez-vous charmer par la palette de couleurs et d'arômes des vins rosés lors de cet atelier exclusif. Découvrez une sélection variée de rosés provenant de différentes régions viticoles, chacun offrant sa propre expression de fraîcheur et de légèreté. Nos sommeliers vous guideront dans cette dégustation en mettant en lumière les nuances subtiles et les accords parfaits pour accompagner ces vins délicats. Préparez-vous à être émerveillé par la finesse et l'élégance de ces vins rosés qui séduisent les palais les plus exigeants.",
        "Rouge"
    ), (
        "2023/08/03 19:00:00",
        "Nice",
        "Explorez un univers gourmand lors de cet atelier dédié aux vins de dessert. Découvrez des vins liquoreux, moelleux et autres nectars sucrés, accompagnés de délices sucrés et de créations pâtissières exquises. Nos sommeliers vous guideront dans cette dégustation sensorielle, vous révélant les accords parfaits entre les vins et les desserts. Laissez-vous séduire par la magie des saveurs sucrées et plongez dans un univers où chaque gorgée vous transportera vers le plaisir gustatif ultime.",
        "Blanc"
    ), (
        "2023/08/06 12:00:00",
        "Strasbourg",
        "Plongez dans l'univers des vins blancs secs lors de cet atelier captivant. Découvrez la diversité des cépages blancs secs provenant de différentes régions viticoles, offrant des profils aromatiques uniques et des caractéristiques variées. Nos sommeliers passionnés partageront avec vous leur expertise et vous guideront à travers cette dégustation immersive, révélant les secrets de chaque vin. Préparez-vous à explorer un monde de fraîcheur et de finesse, où les vins blancs secs éveilleront vos sens et vous feront voyager au cœur des vignobles.",
        "Blanc"
    ), (
        "2023/08/12 13:00:00",
        "Toulouse",
        "Plongez dans l'univers des vins rouges. Une dégustation passionnante vous attend, avec des cépages sélectionnés avec soin pour vous offrir une expérience inoubliable. Rejoignez-nous pour explorer les arômes complexes et les saveurs intenses des vins rouges les plus prestigieux.",
        "Rouge"
    ), (
        "2023/08/12 16:00:00",
        "Toulouse",
        "Atelier dédié aux vins blancs. Laissez-vous séduire par la fraîcheur et l'élégance de ces vins, provenant de différentes régions viticoles. Découvrez les arômes délicats et les nuances subtiles qui font la renommée des vins blancs sélectionnés pour cet atelier.",
        "Blanc"
    ), (
        "2023/08/15 18:30:00",
        "Paris",
        "Explorez les accords mets et vins lors de cet atelier spécial. Plongez dans un voyage gustatif où chaque bouchée est harmonieusement accompagnée d'un vin soigneusement choisi. Nos experts vous guideront dans l'art de marier les saveurs, vous offrant ainsi une expérience culinaire exceptionnelle et mémorable.",
        "Rouge"
    ), (
        "2023/08/16 14:00:00",
        "Bordeaux",
        "Découvrez les vins rouges bio lors de cet atelier de dégustation. Appréciez la qualité et l'authenticité de ces vins issus de pratiques respectueuses de l'environnement. Laissez-vous séduire par leur caractère unique et leur expression du terroir, révélant des saveurs riches et équilibrées.",
        "Rouge"
    ), (
        "2023/08/17 17:00:00",
        "Marseille",
        "Plongez dans le monde des vins effervescents lors de cet atelier festif. Découvrez la magie des bulles et laissez-vous surprendre par la diversité des vins effervescents, des champagnes aux proseccos en passant par les crémants. Éveillez vos papilles avec ces vins pétillants, symboles de célébration et de joie.",
        "Blanc"
    ), (
        "2023/08/18 15:30:00",
        "Lyon",
        "Appréciez la subtilité des vins rosés lors de cet atelier exclusif. Découvrez une sélection variée de rosés aux couleurs délicates et aux arômes frais. Laissez-vous séduire par leur fraîcheur et leur légèreté, et découvrez les accords parfaits pour sublimer ces vins rosés lors d'une dégustation raffinée.",
        "Rouge"
    ), (
        "2023/08/18 19:00:00",
        "Nice",
        "Succombez aux plaisirs des vins de dessert lors de cet atelier gourmand. Découvrez une palette de saveurs sucrées et explorez l'art de l'association entre les vins liquoreux et les délices sucrés. Laissez-vous envoûter par ces accords divins qui éveilleront tous vos sens.",
        "Blanc"
    ), (
        "2023/08/19 12:00:00",
        "Nice",
        "Découvrez la fraîcheur des vins blancs secs lors de cet atelier captivant. Explorez une sélection variée de cépages blancs secs, reflétant la richesse et la diversité des régions viticoles. Laissez-vous emporter par les arômes délicats et les notes fruitées de ces vins qui sauront égayer vos papilles.",
        "Blanc"
    ), (
        "2023/08/23 13:00:00",
        "Lille",
        "Célébrez la Saint-Valentin avec notre atelier spécial vins et chocolats. Plongez dans une expérience sensorielle irrésistible en découvrant l'art de l'association entre les vins et les chocolats fins. Laissez-vous guider par notre sommelier pour créer des accords parfaits entre ces délices sucrés et les vins qui les mettront en valeur.",
        "Divers"
    ), (
        "2023/08/23 17:30:00",
        "Lille",
        "Initiez-vous aux vins naturels lors de cet atelier authentique. Découvrez des vins produits selon des méthodes artisanales, où l'accent est mis sur la simplicité et le respect du terroir. Plongez dans l'univers des vins naturels et laissez-vous séduire par leur expression pure et leur caractère unique.",
        "Naturel"
    ), (
        "2023/07/23 16:00:00",
        "Mende",
        "Troisième atelier",
        "Rouge"
    ), (
        "2023/07/23 16:00:00",
        "Gaillac",
        "Quatrième atelier",
        "Rouge"
    );

-- -----------------------------------------------------

-- Table `inovin`.`olfactive_intensityAromas`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`olfactive_intensityAromas` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `intensity_aromas` VARCHAR(55) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`olfactive_intensityAromas` (`intensity_aromas`)
VALUES ('Discret'), ('Ouvert'), ('Aromatique'), ('Intense'), ('France');

-- -----------------------------------------------------

-- Table `inovin`.`olfactive_complexity`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`olfactive_complexity` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `complexity` VARCHAR(45) NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    inovin.olfactive_complexity (complexity)
VALUES ('Simple'), ('Riche'), ('Très complexe');

-- -----------------------------------------------------

-- Table `inovin`.`visual_color`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`visual_color` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `color` VARCHAR(45) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    inovin.visual_color (color)
VALUES ('Framboise'), ('Cerise'), ('Rubis'), ('Pourpre'), ('Violet'), ('Grenat'), ('Rouge-noir'), ('Tuilé');

-- -----------------------------------------------------

-- Table `inovin`.`visual_limpidity`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`visual_limpidity` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `limpidity` VARCHAR(45) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`visual_limpidity` (`limpidity`)
VALUES ('Transparente'), ('Limpide'), ('Cristalline'), ('Opaque'), ('Voilée'), ('Floue');

-- -----------------------------------------------------

-- Table `inovin`.`visual_brightness`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`visual_brightness` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `brightness` VARCHAR(45) NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`visual_brightness` (`brightness`)
VALUES ('Nette'), ('Etincelante'), ('Eclatante'), ('Brillante'), ('Lumineuse'), ('Terne');

-- -----------------------------------------------------

-- Table `inovin`.`visual_tears`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`visual_tears` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `tears` VARCHAR(45) NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`visual_tears` (tears)
VALUES ('Visqueuses'), ('Grasses'), ('Epaisses'), ('Coulantes'), ('Fluides');

-- -----------------------------------------------------

-- Table `inovin`.`taste_intensity`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`taste_intensity` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `intensity` VARCHAR(45) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`taste_intensity` (intensity)
VALUES ('Discret'), ('Aromatique'), ('Expressif'), ('Explosif');

-- -----------------------------------------------------

-- Table `inovin`.`taste_mouth_feel`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`taste_mouth_feel` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `mouth_feel` VARCHAR(45) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`taste_mouth_feel` (mouth_feel)
VALUES ('Longue'), ('Courte'), ('Persistante'), ('Développée'), ('Rémanente');

-- -----------------------------------------------------

-- Table `inovin`.`taste_alcohol`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`taste_alcohol` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `alcohol` VARCHAR(45) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`taste_alcohol` (alcohol)
VALUES ('Faible '), ('Généreux'), ('Gras'), ('Capiteux'), ('Alcooleux');

-- -----------------------------------------------------

-- Table `inovin`.`acidity`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`acidity` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `acidity` VARCHAR(45) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`acidity`(acidity)
VALUES ('Molle'), ('Fraîche'), ('Vive'), ('Pointue'), ('Nerveuse');

-- -----------------------------------------------------

-- Table `inovin`.`taste_sweetness`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`taste_sweetness` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `sweetness` VARCHAR(45) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`taste_sweetness` (`sweetness`)
VALUES ('Sec'), ('Doux'), ('Moelleux'), ('Liquoreux'), ('Sirupeux');

-- -----------------------------------------------------

-- Table `inovin`.`taste_tannin`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`taste_tannin` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `taste_tannin` VARCHAR(45) NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`taste_tannin` (`taste_tannin`)
VALUES ('Lisse'), ('Fondu'), ('Charpenté'), ('Chargé'), ('Apre');

-- -----------------------------------------------------

-- Table `inovin`.`visual_intensity`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`visual_intensity` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `intensity` VARCHAR(45) NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    inovin.visual_intensity (intensity)
VALUES ('Claire'), ('Soutenue'), ('Intense'), ('Pâle'), ('Foncée'), ('Profonde');

-- -----------------------------------------------------

-- Table `inovin`.`tasting_note`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`tasting_note` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `wine_quality` VARCHAR(45) NOT NULL,
        `id_olfactive_intensity` INT NOT NULL,
        `id_user` INT NOT NULL,
        `rating` DECIMAL(10) NOT NULL,
        `tasting_commentary` LONGTEXT NULL,
        `olfactive_complexity_id` INT NOT NULL,
        `visual_color_id` INT NOT NULL,
        `visual_intensity_id` INT NOT NULL,
        `visual_limpidity_id` INT NOT NULL,
        `visual_brightness_id` INT NOT NULL,
        `visual_tears_id` INT NOT NULL,
        `taste_intensity_id` INT NOT NULL,
        `taste_mouth_feel_id` INT NOT NULL,
        `taste_alcohol_id` INT NOT NULL,
        `acidity_id` INT NOT NULL,
        `taste_sweetness_id` INT NOT NULL,
        `taste_tannin_id` INT NOT NULL,
        PRIMARY KEY (`id`),
        CONSTRAINT `fk_tasting_note_olfactif_intensityAromas1` FOREIGN KEY (`id_olfactive_intensity`) REFERENCES `inovin`.`olfactive_intensityAromas` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_user1` FOREIGN KEY (`id_user`) REFERENCES `inovin`.`user` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_olfactive_complexity1` FOREIGN KEY (`olfactive_complexity_id`) REFERENCES `inovin`.`olfactive_complexity` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_visual_color1` FOREIGN KEY (`visual_color_id`) REFERENCES `inovin`.`visual_color` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_visual_intensity` FOREIGN KEY (`visual_intensity_id`) REFERENCES `inovin`.`visual_intensity` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_visual_limpidity1` FOREIGN KEY (`visual_limpidity_id`) REFERENCES `inovin`.`visual_limpidity` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_visual_brightness1` FOREIGN KEY (`visual_brightness_id`) REFERENCES `inovin`.`visual_brightness` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_visual_tears1` FOREIGN KEY (`visual_tears_id`) REFERENCES `inovin`.`visual_tears` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_taste_intensity1` FOREIGN KEY (`taste_intensity_id`) REFERENCES `inovin`.`taste_intensity` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_taste_mouth_feel1` FOREIGN KEY (`taste_mouth_feel_id`) REFERENCES `inovin`.`taste_mouth_feel` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_taste_alcohol1` FOREIGN KEY (`taste_alcohol_id`) REFERENCES `inovin`.`taste_alcohol` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_acidity1` FOREIGN KEY (`acidity_id`) REFERENCES `inovin`.`acidity` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_taste_sweetness1` FOREIGN KEY (`taste_sweetness_id`) REFERENCES `inovin`.`taste_sweetness` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_taste_tannin1` FOREIGN KEY (`taste_tannin_id`) REFERENCES `inovin`.`taste_tannin` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`tasting_note`(
        wine_quality,
        id_olfactive_intensity,
        id_user,
        rating,
        tasting_commentary,
        olfactive_complexity_id,
        visual_color_id,
        visual_intensity_id,
        visual_limpidity_id,
        visual_brightness_id,
        visual_tears_id,
        taste_intensity_id,
        taste_mouth_feel_id,
        taste_alcohol_id,
        acidity_id,
        taste_sweetness_id,
        taste_tannin_id
    )
VALUES (
        'Bon',
        1,
        2,
        6,
        'Vin très tannique et étonnant',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ), (
        'Très bon',
        1,
        2,
        8,
        'Ce vin rouge est très équilibré.',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ), (
        'Pas terrible',
        1,
        2,
        4,
        'Vin fade',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ), (
        'Mauvais',
        1,
        2,
        3,
        'Ce vin rouge a une mauvaise odeur.',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ), (
        'Parfait',
        1,
        2,
        10,
        'Le meilleur vin de la dégustation.',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ), (
        'Excellent',
        1,
        1,
        8,
        'Vin étonnant',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ), (
        'Très bon',
        1,
        1,
        7,
        'Ce vin blanc est très équilibré.',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ), (
        'Passable',
        1,
        1,
        3,
        'Vin fade',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ), (
        'Mauvais',
        1,
        1,
        3,
        'Je n aime pas les parfums dégagés par ce vin blanc',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ), (
        'Parfait',
        1,
        1,
        9,
        'Le meilleur vin blanc de la dégustation.',
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    );

-- -----------------------------------------------------

-- Table `inovin`.`olfactive_aromas`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`olfactive_aromas` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `aromas` VARCHAR(55) NOT NULL,
        `img_url` LONGTEXT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`olfactive_aromas` (`aromas`)
VALUES ('Epices'), ('Boisé'), ('Floral'), ('Végétal'), ('Fruits'), ('Torréfié'), ('Minéral'), ('Animal');

-- -----------------------------------------------------

-- Table `inovin`.`workshop_has_existingWine`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`workshop_has_existingWine` (
        `id_workshop` INT NOT NULL,
        `id_existing_wine` INT NOT NULL,
        CONSTRAINT `fk_workshop_has_existingWine_workshop1` FOREIGN KEY (`id_workshop`) REFERENCES `inovin`.`workshop` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT `fk_workshop_has_existingWine_existing_wine1` FOREIGN KEY (`id_existing_wine`) REFERENCES `inovin`.`existing_wine` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`workshop_has_existingWine`(id_workshop, id_existing_wine)
VALUES (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10);

-- -----------------------------------------------------

-- Table `inovin`.`tastingnote_has_existingwine`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`tastingnote_has_existingwine` (
        `id_tasting_note` INT NOT NULL,
        `id_existing_wine` INT NOT NULL,
        CONSTRAINT `fk_tasting_note_has_existing_wine_tasting_note1` FOREIGN KEY (`id_tasting_note`) REFERENCES `inovin`.`tasting_note` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_has_existing_wine_existing_wine1` FOREIGN KEY (`id_existing_wine`) REFERENCES `inovin`.`existing_wine` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    inovin.tastingnote_has_existingwine (
        id_tasting_note,
        id_existing_wine
    )
VALUES (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10);

-- -----------------------------------------------------

-- Table `inovin`.`user_has_workshop`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`user_has_workshop` (
        `id_user` INT NOT NULL,
        `id_workshop` INT NOT NULL,
        CONSTRAINT `fk_CANDIDAT_has_Degustation_CANDIDAT1` FOREIGN KEY (`id_user`) REFERENCES `inovin`.`user` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT `fk_CANDIDAT_has_Degustation_Degustation1` FOREIGN KEY (`id_workshop`) REFERENCES `inovin`.`workshop` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`user_has_workshop`(id_user, id_workshop)
VALUES (1, 1), (1, 2), (2, 1), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (2, 2), (2, 14);

-- -----------------------------------------------------

-- Table `inovin`.`olfactive_aromas_has_tasting_note`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`olfactive_aromas_has_tasting_note` (
        `id_olfactive` INT NOT NULL,
        `id_tasting_note` INT NOT NULL,
        CONSTRAINT `fk_Olfactif_aromas_has_tasting_note_Olfactif_aromas1` FOREIGN KEY (`id_olfactive`) REFERENCES `inovin`.`olfactive_aromas` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_Olfactif_aromas_has_tasting_note_tasting_note1` FOREIGN KEY (`id_tasting_note`) REFERENCES `inovin`.`tasting_note` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`olfactive_aromas_has_tasting_note` (id_tasting_note, id_olfactive)
VALUES (1, 1), (1, 2), (1, 5), (2, 2), (2, 3), (2, 5), (3, 2), (3, 4), (3, 5), (4, 1), (4, 4), (4, 5), (5, 2), (5, 3), (5, 6), (6, 2), (6, 5), (6, 5), (7, 1), (7, 4), (7, 6), (8, 2), (8, 4), (8, 5), (9, 2), (9, 2), (9, 6), (10, 2), (10, 4), (10, 6);

-- -----------------------------------------------------

-- Table `inovin`.`taste_flavor`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`taste_flavor` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `flavor` VARCHAR(45) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`taste_flavor` (`flavor`)
VALUES ('Epices'), ('Boisé'), ('Floral'), ('Végétal'), ('Fruits'), ('Torréfié'), ('Minéral'), ('Animal');

-- -----------------------------------------------------

-- Table `inovin`.`tasting_note_has_taste_flavor`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`tasting_note_has_taste_flavor` (
        `id_tasting_note` INT NOT NULL,
        `id_taste_flavor` INT NOT NULL,
        CONSTRAINT `fk_tasting_note_has_taste_flavor_tasting_note1` FOREIGN KEY (`id_tasting_note`) REFERENCES `inovin`.`tasting_note` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT `fk_tasting_note_has_taste_flavor_taste_flavor1` FOREIGN KEY (`id_taste_flavor`) REFERENCES `inovin`.`taste_flavor` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    `inovin`.`tasting_note_has_taste_flavor` (
        id_tasting_note,
        id_taste_flavor
    )
VALUES (1, 2), (1, 4), (1, 5), (2, 2), (2, 4), (2, 5), (3, 2), (3, 4), (3, 5), (4, 1), (4, 2), (4, 5), (5, 2), (5, 3), (5, 4), (6, 2), (6, 4), (6, 5), (7, 1), (7, 4), (7, 6), (8, 2), (8, 4), (8, 5), (9, 2), (9, 1), (9, 5), (10, 2), (10, 3), (10, 6);

-- -----------------------------------------------------

-- Table `inovin`.`existing_wine_has_appellation`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`existing_wine_has_appellation` (
        `id_existing_wine` INT NOT NULL,
        `id_appellation` INT NOT NULL,
        CONSTRAINT `fk_existing_wine_has_appellation_existing_wine1` FOREIGN KEY (`id_existing_wine`) REFERENCES `inovin`.`existing_wine` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_existing_wine_has_appellation_appellation1` FOREIGN KEY (`id_appellation`) REFERENCES `inovin`.`appellation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    inovin.existing_wine_has_appellation (
        id_existing_wine,
        id_appellation
    )
VALUES ('1', '3'), ('2', '31'), ('3', '46'), ('3', '47'), ('3', '58'), ('4', '78'), ('4', '89'), ('5', '54'), ('6', '73'), ('7', '53'), ('8', '4'), ('8', '86'), ('9', '53'), ('10', '68');

-- -----------------------------------------------------

-- Table `inovin`.`selected_wine`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `inovin`.`selected_wine` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `dosage` DECIMAL(5, 1) NULL,
        `id_new_wine` INT NOT NULL,
        `id_tasting_note` INT NOT NULL,
        PRIMARY KEY (`id`),
        CONSTRAINT `fk_selected_wine_new_wine1` FOREIGN KEY (`id_new_wine`) REFERENCES `inovin`.`new_wine` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_selected_wine_tasting_note1` FOREIGN KEY (`id_tasting_note`) REFERENCES `inovin`.`tasting_note` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

INSERT INTO
    inovin.selected_wine (
        dosage,
        id_new_wine,
        id_tasting_note
    )
VALUES (75, 1, 1), (87, 1, 2), (88, 1, 5), (70, 4, 6), (87, 4, 7), (93, 4, 10);

SET SQL_MODE=Traditional;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;